name: "Build Gaia Binary"
description: "Builds the Gaia binary from a ref and uploads it as an artifact."
inputs:
  ref:
    description: "The ref to build the Gaia binary from."
    required: true
    default: "main"
  release_name:
    description: "The name of the release."
    required: true
    default: "gaiad-linux-main"
  remote_commit_sha:
    description: "The sha of the latest commit on the main branch."
    required: true
  github_token:
    description: "The GitHub token."
    required: true
  bot_token:
    description: "The GitHub token for the bot."
    required: true
runs:
  using: "composite"
  steps:

      - name: Install tools
        shell: bash
        run: |
          sudo apt-get install curl jq -y

      - name: Setup environment
        shell: bash
        run: |
          sudo apt install build-essential wget -y

      - name: Install golang
        shell: bash
        run: |
          wget -q https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz

      - name: Update PATH
        shell: bash
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          go version

      - name: Clone and build Gaia
        shell: bash
        run: |
          go version
          export GOTOOLCHAIN=go1.22.4
          git clone https://github.com/cosmos/gaia.git
          cd gaia
          git checkout ${{ inputs.ref }}
          export LDFLAGS="-extldflags=-static"
          export CGO_ENABLED=0
          make build
          cp build/gaiad ~/gaiad-linux
      
      - name: Print gaia version
        shell: bash
        run: |
          ~/gaiad-linux version

      - name: Add release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "~/gaiad-linux"
          name: ${{ inputs.remote_commit_sha }}
          bodyFile: .github/workflows/gaiad-linux-main-body.md
          prerelease: true
          replacesArtifacts: false
          allowUpdates: false
          tag: ${{ inputs.release_name }}
          token: ${{ inputs.github_token }}
          skipIfReleaseExists: true

      - name: Dispatch to cosmos-release-testing repo
        shell: bash
        env:
          SECRET_TOKEN: ${{ inputs.bot_token }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $SECRET_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/hyphacoop/cosmos-release-testing/dispatches \
          -d '{"event_type":"new_main_build","client_payload":{}}'
