name: ICS Linux Build Release

on:  
  workflow_dispatch:

jobs:
  collect_remote_release:
    name: Read latest interchain-security release
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.query_release.outputs.releases }}
    steps:
      - name: Query latest release of the interchain-security repo
        id: query_release
        run: |
          releases=$(curl -s -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/hyphacoop/interchain-security/releases | jq -c '[.[].tag_name]')
          echo "releases=$releases" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [collect_remote_release]
    permissions:
      contents: write
    strategy:
      matrix:
        release: ${{fromJson(needs.collect_remote_release.outputs.releases)}}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build and release
        uses: ./.github/actions/build-ics-binary
        with:
          release: ${{ matrix.release }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [collect_remote_release]
    permissions: write-all
    strategy:
      matrix:
        release: ${{fromJson(needs.collect_remote_release.outputs.releases)}}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: strangelove-ventures/heighliner-build-action@v1.0.2
        with:
          chain: ics
          tag: ${{ matrix.release }}
          git-ref: ${{ matrix.release }}
          github-organization: hyphacoop
          github-repo: interchain-security
          additional-args: "--go-version=1.22.8"
          heighliner-tag: v1.7.0
